/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AuditAction = { 'countdownOverridden' : null } |
  { 'countdownReset' : null } |
  { 'watermarkToggled' : null } |
  { 'signOut' : null } |
  { 'accessGranted' : null } |
  { 'lessonChanged' : null } |
  { 'failedKey' : null } |
  { 'studentChanged' : null } |
  { 'classUpdated' : null } |
  { 'signIn' : null } |
  { 'mediaChanged' : null } |
  { 'classPublished' : null } |
  { 'classLocked' : null } |
  { 'classUnlocked' : null } |
  { 'accessRevoked' : null } |
  { 'classCreated' : null } |
  { 'classDeleted' : null };
export interface AuditEntry {
  'at' : Timestamp,
  'id' : AuditId,
  'action' : AuditAction,
  'detail' : string,
  'actorPrincipal' : Principal,
}
export type AuditId = bigint;
export interface Cell { 'value' : Value, 'name' : string }
export interface Class {
  'id' : ClassId,
  'descriptionEn' : string,
  'descriptionMl' : string,
  'order' : bigint,
  'published' : boolean,
  'createdAt' : Timestamp,
  'locked' : boolean,
  'updatedAt' : Timestamp,
  'titleEn' : string,
  'titleMl' : string,
}
export type ClassId = bigint;
export interface ClassInput {
  'descriptionEn' : string,
  'descriptionMl' : string,
  'published' : boolean,
  'titleEn' : string,
  'titleMl' : string,
}
export type CompleteResult = {
    'ok' : { 'nextClassId' : [] | [ClassId], 'countdownEndsAt' : Timestamp }
  } |
  { 'notAuthorized' : null } |
  { 'alreadyCompleted' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type KeyKind = { 'admin' : null } |
  { 'student' : null };
export interface Lesson {
  'id' : LessonId,
  'files' : Array<MediaRef>,
  'order' : bigint,
  'video' : [] | [MediaRef],
  'bodyEn' : string,
  'bodyMl' : string,
  'classId' : ClassId,
  'titleEn' : string,
  'titleMl' : string,
  'poster' : [] | [MediaRef],
}
export type LessonId = bigint;
export interface LessonInput {
  'bodyEn' : string,
  'bodyMl' : string,
  'classId' : ClassId,
  'titleEn' : string,
  'titleMl' : string,
}
export type MediaId = bigint;
export type MediaKind = { 'video' : null } |
  { 'file' : null } |
  { 'poster' : null };
export interface MediaRef {
  'id' : MediaId,
  'blob' : Uint8Array,
  'kind' : MediaKind,
  'name' : string,
  'mimeType' : string,
  'uploadedAt' : Timestamp,
}
export interface Progress {
  'studentId' : StudentId,
  'currentClassId' : [] | [ClassId],
  'completedClasses' : Array<ClassId>,
  'countdownEndsAt' : [] | [Timestamp],
  'remainingSeconds' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Role = { 'admin' : null } |
  { 'student' : null };
export interface Session {
  'token' : SessionToken,
  'role' : Role,
  'issuedAt' : Timestamp,
}
export type SessionToken = string;
export interface SessionView { 'role' : Role, 'issuedAt' : Timestamp }
export interface Student {
  'id' : StudentId,
  'name' : string,
  'createdAt' : Timestamp,
  'identifier' : string,
  'watermarkEnabled' : boolean,
}
export interface StudentClassView {
  'completed' : boolean,
  'locked' : boolean,
  'countdownEndsAt' : [] | [Timestamp],
  'remainingSeconds' : bigint,
  'classInfo' : Class,
}
export interface StudentDashboard {
  'studentId' : StudentId,
  'totalCount' : bigint,
  'classes' : Array<StudentClassView>,
  'completedCount' : bigint,
  'remainingSeconds' : bigint,
  'currentCountdownEndsAt' : [] | [Timestamp],
}
export type StudentId = bigint;
export interface StudentInput { 'name' : string, 'identifier' : string }
export interface StudentSelfView {
  'id' : StudentId,
  'name' : string,
  'identifier' : string,
  'watermarkEnabled' : boolean,
}
export interface StudentView {
  'progress' : Progress,
  'grantedClasses' : Array<ClassId>,
  'student' : Student,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VerifyResult = { 'ok' : Session } |
  { 'invalidKey' : null } |
  { 'rateLimited' : { 'retryAfterSeconds' : bigint } };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attachLessonMedia' : ActorMethod<
    [
      LessonId,
      { 'video' : null } |
        { 'file' : null } |
        { 'poster' : null },
      string,
      string,
      Uint8Array,
    ],
    [] | [Lesson]
  >,
  'completeClass' : ActorMethod<[StudentId, ClassId], CompleteResult>,
  'createClass' : ActorMethod<[ClassInput], Class>,
  'createLesson' : ActorMethod<[LessonInput], Lesson>,
  'createStudent' : ActorMethod<[StudentInput], Student>,
  'deleteClass' : ActorMethod<[ClassId], boolean>,
  'deleteLesson' : ActorMethod<[LessonId], boolean>,
  'deleteStudent' : ActorMethod<[StudentId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getAuthorizedLessonMedia' : ActorMethod<
    [SessionToken, StudentId, LessonId],
    [] | [Lesson]
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClass' : ActorMethod<[ClassId], [] | [Class]>,
  'getSession' : ActorMethod<[SessionToken], [] | [SessionView]>,
  'getStudent' : ActorMethod<[StudentId], [] | [StudentView]>,
  'getStudentDashboard' : ActorMethod<[StudentId], [] | [StudentDashboard]>,
  'grantClassAccess' : ActorMethod<[StudentId, ClassId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAudit' : ActorMethod<[bigint], Array<AuditEntry>>,
  'listClasses' : ActorMethod<[], Array<Class>>,
  'listLessons' : ActorMethod<[ClassId], Array<Lesson>>,
  'listStudents' : ActorMethod<[], Array<StudentView>>,
  'overrideCountdown' : ActorMethod<[StudentId, ClassId, bigint], boolean>,
  'removeLessonMedia' : ActorMethod<[LessonId, MediaId], [] | [Lesson]>,
  'reorderClasses' : ActorMethod<[Array<ClassId>], undefined>,
  'resetCountdown' : ActorMethod<[StudentId, ClassId], boolean>,
  'resolveStudent' : ActorMethod<[string], [] | [StudentSelfView]>,
  'revokeClassAccess' : ActorMethod<[StudentId, ClassId], boolean>,
  'schema' : ActorMethod<[], string>,
  'setClassLockForStudent' : ActorMethod<
    [StudentId, ClassId, boolean],
    boolean
  >,
  'setClassLocked' : ActorMethod<[ClassId, boolean], [] | [Class]>,
  'setClassPublished' : ActorMethod<[ClassId, boolean], [] | [Class]>,
  'setStudentWatermark' : ActorMethod<[StudentId, boolean], [] | [Student]>,
  'signOut' : ActorMethod<[SessionToken], undefined>,
  'updateClass' : ActorMethod<[ClassId, ClassInput], [] | [Class]>,
  'updateLesson' : ActorMethod<[LessonId, LessonInput], [] | [Lesson]>,
  'updateStudent' : ActorMethod<[StudentId, StudentInput], [] | [Student]>,
  'verifyAccessKey' : ActorMethod<[KeyKind, string], VerifyResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];