/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LessonId = IDL.Nat;
export const MediaId = IDL.Nat;
export const MediaKind = IDL.Variant({
  'video' : IDL.Null,
  'file' : IDL.Null,
  'poster' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const MediaRef = IDL.Record({
  'id' : MediaId,
  'blob' : IDL.Vec(IDL.Nat8),
  'kind' : MediaKind,
  'name' : IDL.Text,
  'mimeType' : IDL.Text,
  'uploadedAt' : Timestamp,
});
export const ClassId = IDL.Nat;
export const Lesson = IDL.Record({
  'id' : LessonId,
  'files' : IDL.Vec(MediaRef),
  'order' : IDL.Nat,
  'video' : IDL.Opt(MediaRef),
  'bodyEn' : IDL.Text,
  'bodyMl' : IDL.Text,
  'classId' : ClassId,
  'titleEn' : IDL.Text,
  'titleMl' : IDL.Text,
  'poster' : IDL.Opt(MediaRef),
});
export const StudentId = IDL.Nat;
export const CompleteResult = IDL.Variant({
  'ok' : IDL.Record({
    'nextClassId' : IDL.Opt(ClassId),
    'countdownEndsAt' : Timestamp,
  }),
  'notAuthorized' : IDL.Null,
  'alreadyCompleted' : IDL.Null,
});
export const ClassInput = IDL.Record({
  'descriptionEn' : IDL.Text,
  'descriptionMl' : IDL.Text,
  'published' : IDL.Bool,
  'titleEn' : IDL.Text,
  'titleMl' : IDL.Text,
});
export const Class = IDL.Record({
  'id' : ClassId,
  'descriptionEn' : IDL.Text,
  'descriptionMl' : IDL.Text,
  'order' : IDL.Nat,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'locked' : IDL.Bool,
  'updatedAt' : Timestamp,
  'titleEn' : IDL.Text,
  'titleMl' : IDL.Text,
});
export const LessonInput = IDL.Record({
  'bodyEn' : IDL.Text,
  'bodyMl' : IDL.Text,
  'classId' : ClassId,
  'titleEn' : IDL.Text,
  'titleMl' : IDL.Text,
});
export const StudentInput = IDL.Record({
  'name' : IDL.Text,
  'identifier' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'identifier' : IDL.Text,
  'watermarkEnabled' : IDL.Bool,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const SessionToken = IDL.Text;
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
export const SessionView = IDL.Record({
  'role' : Role,
  'issuedAt' : Timestamp,
});
export const Progress = IDL.Record({
  'studentId' : StudentId,
  'currentClassId' : IDL.Opt(ClassId),
  'completedClasses' : IDL.Vec(ClassId),
  'countdownEndsAt' : IDL.Opt(Timestamp),
  'remainingSeconds' : IDL.Nat,
});
export const StudentView = IDL.Record({
  'progress' : Progress,
  'grantedClasses' : IDL.Vec(ClassId),
  'student' : Student,
});
export const StudentClassView = IDL.Record({
  'completed' : IDL.Bool,
  'locked' : IDL.Bool,
  'countdownEndsAt' : IDL.Opt(Timestamp),
  'remainingSeconds' : IDL.Nat,
  'classInfo' : Class,
});
export const StudentDashboard = IDL.Record({
  'studentId' : StudentId,
  'totalCount' : IDL.Nat,
  'classes' : IDL.Vec(StudentClassView),
  'completedCount' : IDL.Nat,
  'remainingSeconds' : IDL.Nat,
  'currentCountdownEndsAt' : IDL.Opt(Timestamp),
});
export const AuditId = IDL.Nat;
export const AuditAction = IDL.Variant({
  'countdownOverridden' : IDL.Null,
  'countdownReset' : IDL.Null,
  'watermarkToggled' : IDL.Null,
  'signOut' : IDL.Null,
  'accessGranted' : IDL.Null,
  'lessonChanged' : IDL.Null,
  'failedKey' : IDL.Null,
  'studentChanged' : IDL.Null,
  'classUpdated' : IDL.Null,
  'signIn' : IDL.Null,
  'mediaChanged' : IDL.Null,
  'classPublished' : IDL.Null,
  'classLocked' : IDL.Null,
  'classUnlocked' : IDL.Null,
  'accessRevoked' : IDL.Null,
  'classCreated' : IDL.Null,
  'classDeleted' : IDL.Null,
});
export const AuditEntry = IDL.Record({
  'at' : Timestamp,
  'id' : AuditId,
  'action' : AuditAction,
  'detail' : IDL.Text,
  'actorPrincipal' : IDL.Principal,
});
export const StudentSelfView = IDL.Record({
  'id' : StudentId,
  'name' : IDL.Text,
  'identifier' : IDL.Text,
  'watermarkEnabled' : IDL.Bool,
});
export const KeyKind = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
});
export const Session = IDL.Record({
  'token' : SessionToken,
  'role' : Role,
  'issuedAt' : Timestamp,
});
export const VerifyResult = IDL.Variant({
  'ok' : Session,
  'invalidKey' : IDL.Null,
  'rateLimited' : IDL.Record({ 'retryAfterSeconds' : IDL.Nat }),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attachLessonMedia' : IDL.Func(
      [
        LessonId,
        IDL.Variant({
          'video' : IDL.Null,
          'file' : IDL.Null,
          'poster' : IDL.Null,
        }),
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat8),
      ],
      [IDL.Opt(Lesson)],
      [],
    ),
  'completeClass' : IDL.Func([StudentId, ClassId], [CompleteResult], []),
  'createClass' : IDL.Func([ClassInput], [Class], []),
  'createLesson' : IDL.Func([LessonInput], [Lesson], []),
  'createStudent' : IDL.Func([StudentInput], [Student], []),
  'deleteClass' : IDL.Func([ClassId], [IDL.Bool], []),
  'deleteLesson' : IDL.Func([LessonId], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getAuthorizedLessonMedia' : IDL.Func(
      [SessionToken, StudentId, LessonId],
      [IDL.Opt(Lesson)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClass' : IDL.Func([ClassId], [IDL.Opt(Class)], ['query']),
  'getSession' : IDL.Func([SessionToken], [IDL.Opt(SessionView)], ['query']),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentView)], ['query']),
  'getStudentDashboard' : IDL.Func(
      [StudentId],
      [IDL.Opt(StudentDashboard)],
      ['query'],
    ),
  'grantClassAccess' : IDL.Func([StudentId, ClassId], [IDL.Bool], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAudit' : IDL.Func([IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
  'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
  'listLessons' : IDL.Func([ClassId], [IDL.Vec(Lesson)], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
  'overrideCountdown' : IDL.Func([StudentId, ClassId, IDL.Int], [IDL.Bool], []),
  'removeLessonMedia' : IDL.Func([LessonId, MediaId], [IDL.Opt(Lesson)], []),
  'reorderClasses' : IDL.Func([IDL.Vec(ClassId)], [], []),
  'resetCountdown' : IDL.Func([StudentId, ClassId], [IDL.Bool], []),
  'resolveStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentSelfView)], []),
  'revokeClassAccess' : IDL.Func([StudentId, ClassId], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setClassLockForStudent' : IDL.Func(
      [StudentId, ClassId, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'setClassLocked' : IDL.Func([ClassId, IDL.Bool], [IDL.Opt(Class)], []),
  'setClassPublished' : IDL.Func([ClassId, IDL.Bool], [IDL.Opt(Class)], []),
  'setStudentWatermark' : IDL.Func(
      [StudentId, IDL.Bool],
      [IDL.Opt(Student)],
      [],
    ),
  'signOut' : IDL.Func([SessionToken], [], []),
  'updateClass' : IDL.Func([ClassId, ClassInput], [IDL.Opt(Class)], []),
  'updateLesson' : IDL.Func([LessonId, LessonInput], [IDL.Opt(Lesson)], []),
  'updateStudent' : IDL.Func([StudentId, StudentInput], [IDL.Opt(Student)], []),
  'verifyAccessKey' : IDL.Func([KeyKind, IDL.Text], [VerifyResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LessonId = IDL.Nat;
  const MediaId = IDL.Nat;
  const MediaKind = IDL.Variant({
    'video' : IDL.Null,
    'file' : IDL.Null,
    'poster' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const MediaRef = IDL.Record({
    'id' : MediaId,
    'blob' : IDL.Vec(IDL.Nat8),
    'kind' : MediaKind,
    'name' : IDL.Text,
    'mimeType' : IDL.Text,
    'uploadedAt' : Timestamp,
  });
  const ClassId = IDL.Nat;
  const Lesson = IDL.Record({
    'id' : LessonId,
    'files' : IDL.Vec(MediaRef),
    'order' : IDL.Nat,
    'video' : IDL.Opt(MediaRef),
    'bodyEn' : IDL.Text,
    'bodyMl' : IDL.Text,
    'classId' : ClassId,
    'titleEn' : IDL.Text,
    'titleMl' : IDL.Text,
    'poster' : IDL.Opt(MediaRef),
  });
  const StudentId = IDL.Nat;
  const CompleteResult = IDL.Variant({
    'ok' : IDL.Record({
      'nextClassId' : IDL.Opt(ClassId),
      'countdownEndsAt' : Timestamp,
    }),
    'notAuthorized' : IDL.Null,
    'alreadyCompleted' : IDL.Null,
  });
  const ClassInput = IDL.Record({
    'descriptionEn' : IDL.Text,
    'descriptionMl' : IDL.Text,
    'published' : IDL.Bool,
    'titleEn' : IDL.Text,
    'titleMl' : IDL.Text,
  });
  const Class = IDL.Record({
    'id' : ClassId,
    'descriptionEn' : IDL.Text,
    'descriptionMl' : IDL.Text,
    'order' : IDL.Nat,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'locked' : IDL.Bool,
    'updatedAt' : Timestamp,
    'titleEn' : IDL.Text,
    'titleMl' : IDL.Text,
  });
  const LessonInput = IDL.Record({
    'bodyEn' : IDL.Text,
    'bodyMl' : IDL.Text,
    'classId' : ClassId,
    'titleEn' : IDL.Text,
    'titleMl' : IDL.Text,
  });
  const StudentInput = IDL.Record({
    'name' : IDL.Text,
    'identifier' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'identifier' : IDL.Text,
    'watermarkEnabled' : IDL.Bool,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const SessionToken = IDL.Text;
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const SessionView = IDL.Record({ 'role' : Role, 'issuedAt' : Timestamp });
  const Progress = IDL.Record({
    'studentId' : StudentId,
    'currentClassId' : IDL.Opt(ClassId),
    'completedClasses' : IDL.Vec(ClassId),
    'countdownEndsAt' : IDL.Opt(Timestamp),
    'remainingSeconds' : IDL.Nat,
  });
  const StudentView = IDL.Record({
    'progress' : Progress,
    'grantedClasses' : IDL.Vec(ClassId),
    'student' : Student,
  });
  const StudentClassView = IDL.Record({
    'completed' : IDL.Bool,
    'locked' : IDL.Bool,
    'countdownEndsAt' : IDL.Opt(Timestamp),
    'remainingSeconds' : IDL.Nat,
    'classInfo' : Class,
  });
  const StudentDashboard = IDL.Record({
    'studentId' : StudentId,
    'totalCount' : IDL.Nat,
    'classes' : IDL.Vec(StudentClassView),
    'completedCount' : IDL.Nat,
    'remainingSeconds' : IDL.Nat,
    'currentCountdownEndsAt' : IDL.Opt(Timestamp),
  });
  const AuditId = IDL.Nat;
  const AuditAction = IDL.Variant({
    'countdownOverridden' : IDL.Null,
    'countdownReset' : IDL.Null,
    'watermarkToggled' : IDL.Null,
    'signOut' : IDL.Null,
    'accessGranted' : IDL.Null,
    'lessonChanged' : IDL.Null,
    'failedKey' : IDL.Null,
    'studentChanged' : IDL.Null,
    'classUpdated' : IDL.Null,
    'signIn' : IDL.Null,
    'mediaChanged' : IDL.Null,
    'classPublished' : IDL.Null,
    'classLocked' : IDL.Null,
    'classUnlocked' : IDL.Null,
    'accessRevoked' : IDL.Null,
    'classCreated' : IDL.Null,
    'classDeleted' : IDL.Null,
  });
  const AuditEntry = IDL.Record({
    'at' : Timestamp,
    'id' : AuditId,
    'action' : AuditAction,
    'detail' : IDL.Text,
    'actorPrincipal' : IDL.Principal,
  });
  const StudentSelfView = IDL.Record({
    'id' : StudentId,
    'name' : IDL.Text,
    'identifier' : IDL.Text,
    'watermarkEnabled' : IDL.Bool,
  });
  const KeyKind = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const Session = IDL.Record({
    'token' : SessionToken,
    'role' : Role,
    'issuedAt' : Timestamp,
  });
  const VerifyResult = IDL.Variant({
    'ok' : Session,
    'invalidKey' : IDL.Null,
    'rateLimited' : IDL.Record({ 'retryAfterSeconds' : IDL.Nat }),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attachLessonMedia' : IDL.Func(
        [
          LessonId,
          IDL.Variant({
            'video' : IDL.Null,
            'file' : IDL.Null,
            'poster' : IDL.Null,
          }),
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat8),
        ],
        [IDL.Opt(Lesson)],
        [],
      ),
    'completeClass' : IDL.Func([StudentId, ClassId], [CompleteResult], []),
    'createClass' : IDL.Func([ClassInput], [Class], []),
    'createLesson' : IDL.Func([LessonInput], [Lesson], []),
    'createStudent' : IDL.Func([StudentInput], [Student], []),
    'deleteClass' : IDL.Func([ClassId], [IDL.Bool], []),
    'deleteLesson' : IDL.Func([LessonId], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([StudentId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getAuthorizedLessonMedia' : IDL.Func(
        [SessionToken, StudentId, LessonId],
        [IDL.Opt(Lesson)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClass' : IDL.Func([ClassId], [IDL.Opt(Class)], ['query']),
    'getSession' : IDL.Func([SessionToken], [IDL.Opt(SessionView)], ['query']),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(StudentView)], ['query']),
    'getStudentDashboard' : IDL.Func(
        [StudentId],
        [IDL.Opt(StudentDashboard)],
        ['query'],
      ),
    'grantClassAccess' : IDL.Func([StudentId, ClassId], [IDL.Bool], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAudit' : IDL.Func([IDL.Nat], [IDL.Vec(AuditEntry)], ['query']),
    'listClasses' : IDL.Func([], [IDL.Vec(Class)], ['query']),
    'listLessons' : IDL.Func([ClassId], [IDL.Vec(Lesson)], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(StudentView)], ['query']),
    'overrideCountdown' : IDL.Func(
        [StudentId, ClassId, IDL.Int],
        [IDL.Bool],
        [],
      ),
    'removeLessonMedia' : IDL.Func([LessonId, MediaId], [IDL.Opt(Lesson)], []),
    'reorderClasses' : IDL.Func([IDL.Vec(ClassId)], [], []),
    'resetCountdown' : IDL.Func([StudentId, ClassId], [IDL.Bool], []),
    'resolveStudent' : IDL.Func([IDL.Text], [IDL.Opt(StudentSelfView)], []),
    'revokeClassAccess' : IDL.Func([StudentId, ClassId], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setClassLockForStudent' : IDL.Func(
        [StudentId, ClassId, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'setClassLocked' : IDL.Func([ClassId, IDL.Bool], [IDL.Opt(Class)], []),
    'setClassPublished' : IDL.Func([ClassId, IDL.Bool], [IDL.Opt(Class)], []),
    'setStudentWatermark' : IDL.Func(
        [StudentId, IDL.Bool],
        [IDL.Opt(Student)],
        [],
      ),
    'signOut' : IDL.Func([SessionToken], [], []),
    'updateClass' : IDL.Func([ClassId, ClassInput], [IDL.Opt(Class)], []),
    'updateLesson' : IDL.Func([LessonId, LessonInput], [IDL.Opt(Lesson)], []),
    'updateStudent' : IDL.Func(
        [StudentId, StudentInput],
        [IDL.Opt(Student)],
        [],
      ),
    'verifyAccessKey' : IDL.Func([KeyKind, IDL.Text], [VerifyResult], []),
  });
};

export const init = ({ IDL }) => { return []; };