/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AuditEntry {
    at: Timestamp;
    id: AuditId;
    action: AuditAction;
    detail: string;
    actorPrincipal: Principal;
}
export type AuditId = bigint;
export interface Cell {
    value: Value;
    name: string;
}
export interface Class {
    id: ClassId;
    descriptionEn: string;
    descriptionMl: string;
    order: bigint;
    published: boolean;
    createdAt: Timestamp;
    locked: boolean;
    updatedAt: Timestamp;
    titleEn: string;
    titleMl: string;
}
export type ClassId = bigint;
export interface ClassInput {
    descriptionEn: string;
    descriptionMl: string;
    published: boolean;
    titleEn: string;
    titleMl: string;
}
export type CompleteResult = {
    __kind__: "ok";
    ok: {
        nextClassId?: ClassId;
        countdownEndsAt: Timestamp;
    };
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "alreadyCompleted";
    alreadyCompleted: null;
};
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Lesson {
    id: LessonId;
    files: Array<MediaRef>;
    order: bigint;
    video?: MediaRef;
    bodyEn: string;
    bodyMl: string;
    classId: ClassId;
    titleEn: string;
    titleMl: string;
    poster?: MediaRef;
}
export type LessonId = bigint;
export interface LessonInput {
    bodyEn: string;
    bodyMl: string;
    classId: ClassId;
    titleEn: string;
    titleMl: string;
}
export type MediaId = bigint;
export interface MediaRef {
    id: MediaId;
    blob: Uint8Array;
    kind: MediaKind;
    name: string;
    mimeType: string;
    uploadedAt: Timestamp;
}
export interface Progress {
    studentId: StudentId;
    currentClassId?: ClassId;
    completedClasses: Array<ClassId>;
    countdownEndsAt?: Timestamp;
    remainingSeconds: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface Session {
    token: SessionToken;
    role: Role;
    issuedAt: Timestamp;
}
export type SessionToken = string;
export interface SessionView {
    role: Role;
    issuedAt: Timestamp;
}
export interface Student {
    id: StudentId;
    name: string;
    createdAt: Timestamp;
    identifier: string;
    watermarkEnabled: boolean;
}
export interface StudentClassView {
    completed: boolean;
    locked: boolean;
    countdownEndsAt?: Timestamp;
    remainingSeconds: bigint;
    classInfo: Class;
}
export interface StudentDashboard {
    studentId: StudentId;
    totalCount: bigint;
    classes: Array<StudentClassView>;
    completedCount: bigint;
    remainingSeconds: bigint;
    currentCountdownEndsAt?: Timestamp;
}
export type StudentId = bigint;
export interface StudentInput {
    name: string;
    identifier: string;
}
export interface StudentSelfView {
    id: StudentId;
    name: string;
    identifier: string;
    watermarkEnabled: boolean;
}
export interface StudentView {
    progress: Progress;
    grantedClasses: Array<ClassId>;
    student: Student;
}
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export type VerifyResult = {
    __kind__: "ok";
    ok: Session;
} | {
    __kind__: "invalidKey";
    invalidKey: null;
} | {
    __kind__: "rateLimited";
    rateLimited: {
        retryAfterSeconds: bigint;
    };
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AuditAction {
    countdownOverridden = "countdownOverridden",
    countdownReset = "countdownReset",
    watermarkToggled = "watermarkToggled",
    signOut = "signOut",
    accessGranted = "accessGranted",
    lessonChanged = "lessonChanged",
    failedKey = "failedKey",
    studentChanged = "studentChanged",
    classUpdated = "classUpdated",
    signIn = "signIn",
    mediaChanged = "mediaChanged",
    classPublished = "classPublished",
    classLocked = "classLocked",
    classUnlocked = "classUnlocked",
    accessRevoked = "accessRevoked",
    classCreated = "classCreated",
    classDeleted = "classDeleted"
}
export enum KeyKind {
    admin = "admin",
    student = "student"
}
export enum MediaKind {
    video = "video",
    file = "file",
    poster = "poster"
}
export enum Role {
    admin = "admin",
    student = "student"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    attachLessonMedia(lessonId: LessonId, kind: MediaKind, name: string, mimeType: string, blob: Uint8Array): Promise<Lesson | null>;
    completeClass(studentId: StudentId, classId: ClassId): Promise<CompleteResult>;
    createClass(input: ClassInput): Promise<Class>;
    createLesson(input: LessonInput): Promise<Lesson>;
    createStudent(input: StudentInput): Promise<Student>;
    deleteClass(id: ClassId): Promise<boolean>;
    deleteLesson(id: LessonId): Promise<boolean>;
    deleteStudent(id: StudentId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    getApiDoc(): Promise<string>;
    getAuthorizedLessonMedia(token: SessionToken, studentId: StudentId, lessonId: LessonId): Promise<Lesson | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClass(id: ClassId): Promise<Class | null>;
    getSession(token: SessionToken): Promise<SessionView | null>;
    getStudent(id: StudentId): Promise<StudentView | null>;
    getStudentDashboard(studentId: StudentId): Promise<StudentDashboard | null>;
    grantClassAccess(studentId: StudentId, classId: ClassId): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    listAudit(limit: bigint): Promise<Array<AuditEntry>>;
    listClasses(): Promise<Array<Class>>;
    listLessons(classId: ClassId): Promise<Array<Lesson>>;
    listStudents(): Promise<Array<StudentView>>;
    overrideCountdown(studentId: StudentId, classId: ClassId, endsAt: bigint): Promise<boolean>;
    removeLessonMedia(lessonId: LessonId, mediaId: MediaId): Promise<Lesson | null>;
    reorderClasses(orderedIds: Array<ClassId>): Promise<void>;
    resetCountdown(studentId: StudentId, classId: ClassId): Promise<boolean>;
    resolveStudent(identifier: string): Promise<StudentSelfView | null>;
    revokeClassAccess(studentId: StudentId, classId: ClassId): Promise<boolean>;
    schema(): Promise<string>;
    setClassLockForStudent(studentId: StudentId, classId: ClassId, locked: boolean): Promise<boolean>;
    setClassLocked(id: ClassId, locked: boolean): Promise<Class | null>;
    setClassPublished(id: ClassId, published: boolean): Promise<Class | null>;
    setStudentWatermark(studentId: StudentId, enabled: boolean): Promise<Student | null>;
    signOut(token: SessionToken): Promise<void>;
    updateClass(id: ClassId, input: ClassInput): Promise<Class | null>;
    updateLesson(id: LessonId, input: LessonInput): Promise<Lesson | null>;
    updateStudent(id: StudentId, input: StudentInput): Promise<Student | null>;
    verifyAccessKey(kind: KeyKind, key: string): Promise<VerifyResult>;
}
import type { AuditAction as _AuditAction, AuditEntry as _AuditEntry, AuditId as _AuditId, Cell as _Cell, Class as _Class, ClassId as _ClassId, CompleteResult as _CompleteResult, Error as _Error, KeyKind as _KeyKind, Lesson as _Lesson, LessonId as _LessonId, MediaId as _MediaId, MediaKind as _MediaKind, MediaRef as _MediaRef, Progress as _Progress, Result as _Result, Result__1 as _Result__1, Role as _Role, Session as _Session, SessionToken as _SessionToken, SessionView as _SessionView, Student as _Student, StudentClassView as _StudentClassView, StudentDashboard as _StudentDashboard, StudentId as _StudentId, StudentSelfView as _StudentSelfView, StudentView as _StudentView, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, VerifyResult as _VerifyResult, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async attachLessonMedia(arg0: LessonId, arg1: MediaKind, arg2: string, arg3: string, arg4: Uint8Array): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.attachLessonMedia(arg0, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.attachLessonMedia(arg0, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeClass(arg0: StudentId, arg1: ClassId): Promise<CompleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.completeClass(arg0, arg1);
                return from_candid_CompleteResult_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeClass(arg0, arg1);
            return from_candid_CompleteResult_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createClass(arg0: ClassInput): Promise<Class> {
        if (this.processError) {
            try {
                const result = await this.actor.createClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClass(arg0);
            return result;
        }
    }
    async createLesson(arg0: LessonInput): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(arg0);
                return from_candid_Lesson_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(arg0);
            return from_candid_Lesson_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStudent(arg0: StudentInput): Promise<Student> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(arg0);
            return result;
        }
    }
    async deleteClass(arg0: ClassId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClass(arg0);
            return result;
        }
    }
    async deleteLesson(arg0: LessonId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: StudentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getAuthorizedLessonMedia(arg0: SessionToken, arg1: StudentId, arg2: LessonId): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuthorizedLessonMedia(arg0, arg1, arg2);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuthorizedLessonMedia(arg0, arg1, arg2);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClass(arg0: ClassId): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClass(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClass(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: SessionToken): Promise<SessionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: StudentId): Promise<StudentView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentDashboard(arg0: StudentId): Promise<StudentDashboard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentDashboard(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentDashboard(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantClassAccess(arg0: StudentId, arg1: ClassId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.grantClassAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantClassAccess(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAudit(arg0: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAudit(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAudit(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listClasses(): Promise<Array<Class>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClasses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClasses();
            return result;
        }
    }
    async listLessons(arg0: ClassId): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLessons(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLessons(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async listStudents(): Promise<Array<StudentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudents();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudents();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async overrideCountdown(arg0: StudentId, arg1: ClassId, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.overrideCountdown(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.overrideCountdown(arg0, arg1, arg2);
            return result;
        }
    }
    async removeLessonMedia(arg0: LessonId, arg1: MediaId): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.removeLessonMedia(arg0, arg1);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeLessonMedia(arg0, arg1);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async reorderClasses(arg0: Array<ClassId>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reorderClasses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reorderClasses(arg0);
            return result;
        }
    }
    async resetCountdown(arg0: StudentId, arg1: ClassId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.resetCountdown(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetCountdown(arg0, arg1);
            return result;
        }
    }
    async resolveStudent(arg0: string): Promise<StudentSelfView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveStudent(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveStudent(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async revokeClassAccess(arg0: StudentId, arg1: ClassId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeClassAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeClassAccess(arg0, arg1);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setClassLockForStudent(arg0: StudentId, arg1: ClassId, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setClassLockForStudent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setClassLockForStudent(arg0, arg1, arg2);
            return result;
        }
    }
    async setClassLocked(arg0: ClassId, arg1: boolean): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setClassLocked(arg0, arg1);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setClassLocked(arg0, arg1);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async setClassPublished(arg0: ClassId, arg1: boolean): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setClassPublished(arg0, arg1);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setClassPublished(arg0, arg1);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async setStudentWatermark(arg0: StudentId, arg1: boolean): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setStudentWatermark(arg0, arg1);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStudentWatermark(arg0, arg1);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async signOut(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.signOut(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signOut(arg0);
            return result;
        }
    }
    async updateClass(arg0: ClassId, arg1: ClassInput): Promise<Class | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClass(arg0, arg1);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClass(arg0, arg1);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateLesson(arg0: LessonId, arg1: LessonInput): Promise<Lesson | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, arg1);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, arg1);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStudent(arg0: StudentId, arg1: StudentInput): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0, arg1);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0, arg1);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAccessKey(arg0: KeyKind, arg1: string): Promise<VerifyResult> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAccessKey(to_candid_KeyKind_n60(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_VerifyResult_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAccessKey(to_candid_KeyKind_n60(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_VerifyResult_n61(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuditAction_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditAction): AuditAction {
    return "countdownOverridden" in value ? AuditAction.countdownOverridden : "countdownReset" in value ? AuditAction.countdownReset : "watermarkToggled" in value ? AuditAction.watermarkToggled : "signOut" in value ? AuditAction.signOut : "accessGranted" in value ? AuditAction.accessGranted : "lessonChanged" in value ? AuditAction.lessonChanged : "failedKey" in value ? AuditAction.failedKey : "studentChanged" in value ? AuditAction.studentChanged : "classUpdated" in value ? AuditAction.classUpdated : "signIn" in value ? AuditAction.signIn : "mediaChanged" in value ? AuditAction.mediaChanged : "classPublished" in value ? AuditAction.classPublished : "classLocked" in value ? AuditAction.classLocked : "classUnlocked" in value ? AuditAction.classUnlocked : "accessRevoked" in value ? AuditAction.accessRevoked : "classCreated" in value ? AuditAction.classCreated : "classDeleted" in value ? AuditAction.classDeleted : value;
}
function from_candid_AuditEntry_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditEntry): AuditEntry {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CompleteResult_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompleteResult): CompleteResult {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_MediaKind_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaKind): MediaKind {
    return "video" in value ? MediaKind.video : "file" in value ? MediaKind.file : "poster" in value ? MediaKind.poster : value;
}
function from_candid_MediaRef_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaRef): MediaRef {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Progress_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Progress): Progress {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return "admin" in value ? Role.admin : "student" in value ? Role.student : value;
}
function from_candid_SessionView_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionView): SessionView {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Session_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_StudentClassView_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentClassView): StudentClassView {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_StudentDashboard_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentDashboard): StudentDashboard {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_StudentView_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentView): StudentView {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_VerifyResult_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VerifyResult): VerifyResult {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Lesson]): Lesson | null {
    return value.length === 0 ? null : from_candid_Lesson_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MediaRef]): MediaRef | null {
    return value.length === 0 ? null : from_candid_MediaRef_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ClassId]): ClassId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Class]): Class | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionView]): SessionView | null {
    return value.length === 0 ? null : from_candid_SessionView_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentView]): StudentView | null {
    return value.length === 0 ? null : from_candid_StudentView_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentDashboard]): StudentDashboard | null {
    return value.length === 0 ? null : from_candid_StudentDashboard_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentSelfView]): StudentSelfView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LessonId;
    files: Array<_MediaRef>;
    order: bigint;
    video: [] | [_MediaRef];
    bodyEn: string;
    bodyMl: string;
    classId: _ClassId;
    titleEn: string;
    titleMl: string;
    poster: [] | [_MediaRef];
}): {
    id: LessonId;
    files: Array<MediaRef>;
    order: bigint;
    video?: MediaRef;
    bodyEn: string;
    bodyMl: string;
    classId: ClassId;
    titleEn: string;
    titleMl: string;
    poster?: MediaRef;
} {
    return {
        id: value.id,
        files: from_candid_vec_n17(_uploadFile, _downloadFile, value.files),
        order: value.order,
        video: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.video)),
        bodyEn: value.bodyEn,
        bodyMl: value.bodyMl,
        classId: value.classId,
        titleEn: value.titleEn,
        titleMl: value.titleMl,
        poster: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.poster))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MediaId;
    blob: Uint8Array;
    kind: _MediaKind;
    name: string;
    mimeType: string;
    uploadedAt: _Timestamp;
}): {
    id: MediaId;
    blob: Uint8Array;
    kind: MediaKind;
    name: string;
    mimeType: string;
    uploadedAt: Timestamp;
} {
    return {
        id: value.id,
        blob: value.blob,
        kind: from_candid_MediaKind_n20(_uploadFile, _downloadFile, value.kind),
        name: value.name,
        mimeType: value.mimeType,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nextClassId: [] | [_ClassId];
    countdownEndsAt: _Timestamp;
}): {
    nextClassId?: ClassId;
    countdownEndsAt: Timestamp;
} {
    return {
        nextClassId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.nextClassId)),
        countdownEndsAt: value.countdownEndsAt
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n28(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n32(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    role: _Role;
    issuedAt: _Timestamp;
}): {
    role: Role;
    issuedAt: Timestamp;
} {
    return {
        role: from_candid_Role_n39(_uploadFile, _downloadFile, value.role),
        issuedAt: value.issuedAt
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    progress: _Progress;
    grantedClasses: Array<_ClassId>;
    student: _Student;
}): {
    progress: Progress;
    grantedClasses: Array<ClassId>;
    student: Student;
} {
    return {
        progress: from_candid_Progress_n43(_uploadFile, _downloadFile, value.progress),
        grantedClasses: value.grantedClasses,
        student: value.student
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: _StudentId;
    currentClassId: [] | [_ClassId];
    completedClasses: Array<_ClassId>;
    countdownEndsAt: [] | [_Timestamp];
    remainingSeconds: bigint;
}): {
    studentId: StudentId;
    currentClassId?: ClassId;
    completedClasses: Array<ClassId>;
    countdownEndsAt?: Timestamp;
    remainingSeconds: bigint;
} {
    return {
        studentId: value.studentId,
        currentClassId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.currentClassId)),
        completedClasses: value.completedClasses,
        countdownEndsAt: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.countdownEndsAt)),
        remainingSeconds: value.remainingSeconds
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: _StudentId;
    totalCount: bigint;
    classes: Array<_StudentClassView>;
    completedCount: bigint;
    remainingSeconds: bigint;
    currentCountdownEndsAt: [] | [_Timestamp];
}): {
    studentId: StudentId;
    totalCount: bigint;
    classes: Array<StudentClassView>;
    completedCount: bigint;
    remainingSeconds: bigint;
    currentCountdownEndsAt?: Timestamp;
} {
    return {
        studentId: value.studentId,
        totalCount: value.totalCount,
        classes: from_candid_vec_n49(_uploadFile, _downloadFile, value.classes),
        completedCount: value.completedCount,
        remainingSeconds: value.remainingSeconds,
        currentCountdownEndsAt: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.currentCountdownEndsAt))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: boolean;
    locked: boolean;
    countdownEndsAt: [] | [_Timestamp];
    remainingSeconds: bigint;
    classInfo: _Class;
}): {
    completed: boolean;
    locked: boolean;
    countdownEndsAt?: Timestamp;
    remainingSeconds: bigint;
    classInfo: Class;
} {
    return {
        completed: value.completed,
        locked: value.locked,
        countdownEndsAt: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.countdownEndsAt)),
        remainingSeconds: value.remainingSeconds,
        classInfo: value.classInfo
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    at: _Timestamp;
    id: _AuditId;
    action: _AuditAction;
    detail: string;
    actorPrincipal: Principal;
}): {
    at: Timestamp;
    id: AuditId;
    action: AuditAction;
    detail: string;
    actorPrincipal: Principal;
} {
    return {
        at: value.at,
        id: value.id,
        action: from_candid_AuditAction_n55(_uploadFile, _downloadFile, value.action),
        detail: value.detail,
        actorPrincipal: value.actorPrincipal
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: _SessionToken;
    role: _Role;
    issuedAt: _Timestamp;
}): {
    token: SessionToken;
    role: Role;
    issuedAt: Timestamp;
} {
    return {
        token: value.token,
        role: from_candid_Role_n39(_uploadFile, _downloadFile, value.role),
        issuedAt: value.issuedAt
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        nextClassId: [] | [_ClassId];
        countdownEndsAt: _Timestamp;
    };
} | {
    notAuthorized: null;
} | {
    alreadyCompleted: null;
}): {
    __kind__: "ok";
    ok: {
        nextClassId?: ClassId;
        countdownEndsAt: Timestamp;
    };
} | {
    __kind__: "notAuthorized";
    notAuthorized: null;
} | {
    __kind__: "alreadyCompleted";
    alreadyCompleted: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n24(_uploadFile, _downloadFile, value.ok)
    } : "notAuthorized" in value ? {
        __kind__: "notAuthorized",
        notAuthorized: value.notAuthorized
    } : "alreadyCompleted" in value ? {
        __kind__: "alreadyCompleted",
        alreadyCompleted: value.alreadyCompleted
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Session;
} | {
    invalidKey: null;
} | {
    rateLimited: {
        retryAfterSeconds: bigint;
    };
}): {
    __kind__: "ok";
    ok: Session;
} | {
    __kind__: "invalidKey";
    invalidKey: null;
} | {
    __kind__: "rateLimited";
    rateLimited: {
        retryAfterSeconds: bigint;
    };
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Session_n63(_uploadFile, _downloadFile, value.ok)
    } : "invalidKey" in value ? {
        __kind__: "invalidKey",
        invalidKey: value.invalidKey
    } : "rateLimited" in value ? {
        __kind__: "rateLimited",
        rateLimited: value.rateLimited
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaRef>): Array<MediaRef> {
    return value.map((x)=>from_candid_MediaRef_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentClassView>): Array<StudentClassView> {
    return value.map((x)=>from_candid_StudentClassView_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditEntry>): Array<AuditEntry> {
    return value.map((x)=>from_candid_AuditEntry_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentView>): Array<StudentView> {
    return value.map((x)=>from_candid_StudentView_n41(_uploadFile, _downloadFile, x));
}
function to_candid_KeyKind_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KeyKind): _KeyKind {
    return value == KeyKind.admin ? {
        admin: null
    } : value == KeyKind.student ? {
        student: null
    } : value;
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaKind): {
    video: null;
} | {
    file: null;
} | {
    poster: null;
} {
    return value == MediaKind.video ? {
        video: null
    } : value == MediaKind.file ? {
        file: null
    } : value == MediaKind.poster ? {
        poster: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
